### ISSUE TITLE
As a renter I should be able to block/report rentees if they violate community guidelines for the betterment of other renters and the platform

### ISSUE THREAD

**Issue by dc5212** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#10]
**Acceptance Criteria**

A renter should be able to report or block the rentee and then in the future, the rentee shouldn't be able to see the renter's listings or profile or get the option to contact them and renter should also not get the option to contact the rentee

**Comment by himanshu1196** [comment]
redundant
