### ISSUE TITLE
Testing Feedback: DefaultProfile.jpg Failed to Load

### ISSUE THREAD

**Issue by NigelLu** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#176]
Hi Team 4,

After I log in, I noticed that the default profile picture for my account is not loading. The GET request to endpoint "https://elasticbeanstalk-us-west-2-785224258848.s3.amazonaws.com/static/DefaultProfile.jpg" got 403 Forbidden as response. I looked into your codebase and noticed that you have placed your DefaultProfile.jpg under `media` folder instead of static. So you may wanna change your default value for profile picture link in the database modeel. See the screenshot below for more details.

<img width="1199" alt="Screenshot 2023-11-16 at 14 15 21" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/52246554/26c95683-d404-437b-9751-da9b7268f59c">

Hope this is helpful and comment on this issue if you have any question.

**Comment by NigelLu** [comment]
And after uploading a picture of my own, it does work.

<img width="1199" alt="Screenshot 2023-11-16 at 14 16 36" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/52246554/20ae2221-92f3-4edd-a1c0-50856b471b46">

**Comment by himanshu1196** [comment]
Known issue- only images uploaded before the last prod migration were not accessible. Fixed earlier but not yet deployed to prod
