### ISSUE TITLE
Testing Party: Not logged in user accessing a listing detail page will be redirected to a 404

### ISSUE THREAD

**Issue by WenjunYuAnny** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#179]
You website looks amazing! I noticed that if a user is not logged in, and then accesses the listing detail page through the url, the page will be directed to a 404. In a real scenario, I think it's very likely that a user copy the listing url and then share with other people. Then other people will visit the website through this url directly. I guess ideally you might want to redirect the user to a  log in or sign up page.
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/130470692/95058a40-1cde-42eb-861f-96a317e127bc)
Following this line, I think it's also a very likely scenario that a user opens multiple tabs of your website but logs out on one tab. Then the user continues on the other tabs. In this case, the Home/My shortlist/Switch Status will also lead to a 404 currently.

**Comment by himanshu1196** [comment]
Duplicate issue - planned enhancement
