### ISSUE TITLE
As a rentee I should be able to block/report renters if they violate community guidelines for the betterment of other rentees and the platform

### ISSUE THREAD

**Issue by dc5212** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#18]
**Acceptance Criteria**

A rentee should be able to report or block the renter and then in the future, the renter shouldn't be able to see the rentee's profile or get the option to contact them and rentee should also not get the option to contact the renter

**Comment by himanshu1196** [comment]
redundant
