### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by Dhiren-NYU** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#180]
I went to this link after loging in through team3 id
http://production-team4-2-dev3.us-west-2.elasticbeanstalk.com/rrapp/rentee/11/listings/4

and then i changed link to
http://production-team4-2-dev3.us-west-2.elasticbeanstalk.com/rrapp/rentee/12/listings/4
And my profile info changed to account info of team4
I didnt enter password to team4 i shouldnt directly have access to someone's account by changing the link.
After clicking edit button in profile i was able to edit team4's profile details for which i never logged in
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/144502280/ba1b9eab-12b9-4067-ab7a-a8712c76aff3)

**Comment by himanshu1196** [comment]
Thanks for checking this. A bug has already been reported on this so marking it as a duplicate.
