### ISSUE TITLE
Testing Party: Image seems to be broken after User Login

### ISSUE THREAD

**Issue by SushieeK** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#181]
After I login with the team 3 credentials, on the Home page, towards top left, I see a broken image

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/127150757/ba30d4c3-5f4b-4548-96ab-263efafda8ac)

**Comment by himanshu1196** [comment]
Known issue for images uploaded before the last prod migration. Already fixed but yet to be deployed to prod.
