### ISSUE TITLE
Testing Party: 413 Error while I try to upload a picture to the user Profiule

### ISSUE THREAD

**Issue by SushieeK** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#182]
I tried to login as Team 3 user and I tried to upload a picture to the Profile picture, ands I land at 413 Request Entity Too Large error

<img width="1440" alt="image" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/127150757/c53505a5-37e1-4403-bc1b-2899ddeba6a1">

**Comment by himanshu1196** [comment]
Known issue. It is mentioned in the test party doc.

**Comment by Ahmedsavetheplant** [comment]
I cant find test party doc.
