### ISSUE TITLE
Testing Party: Listing Images is Broken 

### ISSUE THREAD

**Issue by SushieeK** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#184]
When i navigate to see  Listings, I see that images are broken. 
May be you need to change files to media. While the new images uploaded looks good.

<img width="1440" alt="image" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/127150757/f8309b17-6c20-4e08-926e-ccf8c7deb9a4">

**Comment by himanshu1196** [comment]
Known issue about old images which were uploaded before last prod migration. Already fixed, but yet to be deployed to prod. New images should be displayed without any errors.
