### ISSUE TITLE
Testing Party: Shortlist + adding myself

### ISSUE THREAD

**Issue by yp2353** [gcivil-nyu-org/Wednesday-Fall2023-Team-4#187]
I am able to shortlist my own listings, and add/message/block my own account

<img width="545" alt="Screen Shot 2023-11-17 at 11 31 28 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-4/assets/113962530/b595fc63-7a71-449f-bf34-757790828606">

**Comment by himanshu1196** [comment]
Yes, this is known but not a bug. Since this does not affect the user experience or the app's functionality, we are not planning to change this behavior in the near future.
